output "namespace" {
  description = "Namespace ArgoCD was installed into"
  value       = helm_release.argocd.namespace
}

output "chart_version" {
  description = "Installed chart version — surfaced so a drift check can compare against what is pinned"
  value       = helm_release.argocd.version
}

# The admin password is generated by the chart into a Secret. Deliberately not an
# output: putting it here would write it into Terraform state in plaintext, and
# state is shared with CI.
output "initial_password_command" {
  description = "How to read the generated admin password"
  value       = "kubectl -n ${helm_release.argocd.namespace} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d"
}

output "port_forward_command" {
  description = "How to reach the UI before an ingress exists"
  value       = "kubectl -n ${helm_release.argocd.namespace} port-forward svc/argocd-server 8080:80"
}
